### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [cornflourblue/angular-7-communicating-between-components#1]
I cloned your project. How do I run it? I'm an Angular newbie. Usually "ng serve" works, but not your project. I get:

```
The serve command requires to be run in an Angular project, but a project definition could not be found.
```

**Comment by cornflourblue** [comment]
`ng serve` is for Angular CLI projects, this project uses Webpack directly not Angular CLI, to start it run `npm install` and `npm start`. Full instructions are on the blog post at http://jasonwatmore.com/post/2019/02/07/angular-7-communicating-between-components-with-observable-subject
